apiVersion: v1
kind: Pod
metadata:
  name: interactive
spec:
  containers:
  - name: interactive
    image: ubuntu:latest
    command: ["sh", "-c", "apt update -y && sleep 1h"]
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: /root
    resources:
      limits:
        memory: 128Mi
        cpu: 1
  volumes:
  - name: secret-volume
    secret:
      secretName: s3
  restartPolicy: Never
