apiVersion: batch/v1
kind: Job
metadata:
  name: sieve
spec:
  template:
    spec:
      containers:
      - name: sieve
        image: ubuntu:latest
        command: ["/bin/sh", "-c"]
        args:
        - export DEBIAN_FRONTEND=noninteractive;
          export MPLCONFIGDIR=/research;
          apt-get update -y >> apt_logs.txt 2>&1 &&
          apt-get install -y git clang libopenblas-dev >> apt_logs.txt 2>&1 &&
          git clone https://github.com/simurgh9/research.git &&
          cd /research/code/experiment;
          clang -L /usr/lib/x86_64-linux-gnu/openblas-pthread/ -I /usr/include/x86_64-linux-gnu/openblas-pthread/ -Ofast -lopenblas -lm sieve.c &&
          ./a.out;
        resources:
          limits:
            memory: 200Gi
            cpu: 220
          requests:
            memory: 176Gi
            cpu: 200
      restartPolicy: Never
