apiVersion: batch/v1
kind: Job
metadata:
  name: bean
spec:
  template:
    spec:
      containers:
      - name: solver
        image: ubuntu:latest
        command: ["/bin/sh", "-c"]
        args:
        - export DEBIAN_FRONTEND=noninteractive;
          apt-get update -y >> apt_logs.txt 2>&1 &&
          apt-get install -y python3 python3-pip python3-wheel s3cmd git >> apt_logs.txt 2>&1 &&
          git clone https://github.com/simurgh9/research.git &&
          cd /research/saved;
          s3cmd get s3://tokari/half_gaps.bin >> s3cmd_logs.txt 2>&1 &&
          cd /research/code;
          pip install . >> /opt/pip_logs.txt 2>&1 &&
          cd /research/code/experiment;
          pytest -vvv --durations=0;
        resources:
          limits:
            memory: 16Gi
            cpu: 8
          requests:
            memory: 128Mi
            cpu: 1
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /root
      volumes:
      - name: secret-volume
        secret:
          secretName: s3
      restartPolicy: Never
