apiVersion: batch/v1
kind: Job
metadata:
  name: bean
spec:
  template:
    spec:
      containers:
      - name: solver
        image: ubuntu:latest
        command: ["/bin/sh", "-c"]
        args:
        - apt update -y &&
          apt install -y python3 python3-pip python3-wheel wget;
          cd /opt/repo/research/saved;
          wget https://www.dropbox.com/s/msb71j7eqevo0d7/half_gaps.bin &&
          ls -al;          
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 256Mi
            cpu: 2
          requests:
            memory: 128Mi
            cpu: 1
      initContainers:
      - name: cloner
        image: alpine/git
        args:
          - clone
          - --single-branch
          - https://github.com/simurgh9/research.git
          - /opt/repo/research
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
      volumes:
      - name: git-repo
        emptyDir: {}
      restartPolicy: Never
