apiVersion: v1
kind: Pod
metadata:
  name: interactive
spec:
  containers:
  - name: interactive
    image: ubuntu:latest
    resources:
      limits:
        memory: 128Mi
        cpu: 1
    command: ["sh", "-c", "apt update -y && apt install -y neofetch && sleep 1h"]
