apiVersion: batch/v1
kind: Job
metadata:
  name: bean
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: bean
        image: ubuntu:latest
        command: ["sh", "-c", "echo Results: 42"]
        resources:
          limits:
            memory: 256Mi
            cpu: 2
          requests:
            memory: 64Mi
            cpu: 1
